### ISSUE TITLE
MySQL StatefulSet 部署失败

### ISSUE THREAD

**Issue by jugggao** [Mr-Linus/k8s-example#1]
使用您的部署案例密码总是被拒绝：

```bash
kubectl get pods
NAME      READY     STATUS                  RESTARTS   AGE
mysql-0   2/2       Running                 0          8m
mysql-1   0/2       Init:CrashLoopBackOff   6          8m

kubectl logs mysql-1 -c clone-mysql
+ [[ -d /var/lib/mysql/mysql ]]
++ hostname
+ [[ mysql-1 =~ -([0-9]+)$ ]]
+ ordinal=1
+ [[ 1 -eq 0 ]]
+ ncat --recv-only mysql-0.mysql 3307
+ xbstream -x -C /var/lib/mysql
+ xtrabackup --prepare --target-dir=/var/lib/mysql
xtrabackup version 2.4.4 based on MySQL server 5.7.13 Linux (x86_64) (revision id: df58cf2)
xtrabackup: cd to /var/lib/mysql
xtrabackup: Error: cannot open ./xtrabackup_checkpoints
xtrabackup: error: xtrabackup_read_metadata()
xtrabackup: This target seems not to have correct metadata...
InnoDB: Number of pools: 1
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.
xtrabackup: Error: xtrabackup_init_temp_log() failed.

kubectl exec -ti mysql-0 -c mysql /bin/bash
root@mysql-0:/# echo -n $MYSQL_ROOT_PASSWORD
testroot@mysql-0:/# mysql -uroot -ptest
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@mysql-0:/# 
```
我在 Pod 中试验密码是正确的：

pod yaml 文件如下：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
      - name: MYSQL_ROOT_PASSWORD
#        value: test
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      ports:
      - name: mysql
        containerPort: 3306
```
```bash
kubectl create -f mysql-pod.yaml 
pod/mysql created

kubectl exec -ti mysql /bin/bash
root@mysql:/# mysql -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"
mysql: [Warning] Using a password on the command line interface can be insecure.
+---+
| 1 |
+---+
| 1 |
+---+
```

很奇怪，为什么在 StatefulSet 里面密码就被拒绝了呢？
